FROM python:3.12.9

RUN python -m pip install --upgrade pip
RUN mkdir /consistency
RUN mkdir /consistency/data

#CUDA
RUN wget https://developer.download.nvidia.com/compute/cuda/repos/wsl-ubuntu/x86_64/cuda-keyring_1.1-1_all.deb
RUN dpkg -i cuda-keyring_1.1-1_all.deb
RUN apt-get update
RUN apt-get -y install cuda-toolkit-12-6
RUN export PATH=${PATH}:/usr/local/cuda-12.6/bin

#Torch + Spacy + Fast Api
COPY ./requirements.txt /consistency/requirements.txt
RUN pip install --default-timeout=1000 -r ./consistency/requirements.txt --extra-index-url https://download.pytorch.org/whl/cu126

#CUDA for docker on wsl2 requires docker ver. 4.31+ and nvidia drivers 555.85+ https://github.com/NVIDIA/nvidia-container-toolkit/issues/520
#Torch + Spacy
#RUN pip install torch torchvision --index-url https://download.pytorch.org/whl/cu126
#RUN pip install -U "spacy[cuda126,transformers,lookups]"
#RUN pip install cupy-cuda12x


#FastApi
#RUN pip install 'fastapi[standard]'

#Copy Python Scripts
COPY . /consistency
WORKDIR /consistency

CMD ["fastapi", "run", "/consistency/Run.py", "--host", "0.0.0.0", "--port"," 8000"]
#docker build -t consistency_container .\dockerize\consistency_container\
#docker run -dit --gpus=all --name consistency_checker -p 8000:8000 -v D:\Informatyka\Magisterka\code\NamedEntity-Goldify\dockerize\containers_data\spacy:/consistency/data consistency_checker