FROM python:3.12.9

RUN mkdir /consistency
RUN mkdir /consistency/data
COPY ./requirements.txt /consistency/requirements.txt
RUN python -m pip install --upgrade pip
RUN pip install --default-timeout=1000 -r ./consistency/requirements.txt
#download spacy models 
COPY . /consistency
WORKDIR /consistency

CMD ["fastapi", "run", "/consistency/Run.py", "--host", "0.0.0.0", "--port"," 8000"]
#CMD [ "python", "./Run.py" ]
#docker build -t consistency_container .\dockerize\consistency_container\